# Generated by Django 5.2 on 2025-05-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapinglog',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapinglog',
            name='error_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
