# Generated by Django 5.2 on 2025-06-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrap', '0002_scrapinglog_ended_at_scrapinglog_error_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('content', models.TextField()),
                ('url', models.URLField(unique=True)),
                ('category', models.CharField(max_length=100)),
                ('is_fake', models.BooleanField()),
            ],
            options={
                'indexes': [models.Index(fields=['url'], name='Scrap_news_url_475511_idx')],
            },
        ),
    ]
