# Generated by Django 5.2 on 2025-06-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrap', '0003_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='url_hash',
            field=models.CharField(default=0, max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
